- README.md
- eth_utils/__init__.py
- eth_utils/encoding/__init__.py
- eth_utils/encoding/py2.py
- eth_utils/encoding/py3.py
- tests/encoding-utils/test_big_endian_integer.py
Add big endian integer encoding/decoding utils.
> add big endian integer utilities

- README.md
- eth_utils/__init__.py
- eth_utils/address.py
- eth_utils/hexidecimal.py
- tests/hexidecimal-utils/test_is_hex.py
Needed a helper function to determine if a string was valid hexidecimal
Added one
> Add is_hex helper

- eth_utils/functional.py
- requirements-dev.txt
- setup.py
[Issue 14](https://github.com/pipermerriam/ethereum-utils/issues/14)
Migrated to cytoolz. Checked against existing tests.
> [issue 14] migrate from toolz to cytoolz

- .gitignore
- README.md
- eth_utils/address.py
- tests/address-utils/test_address_utils.py
- tox.ini
@see https://github.com/pipermerriam/web3.py/issues/227
> is_address() now confirms that the checksum is valid

- README.md
Currency conversions were missing documentation.
> add docs for currency conversions

- tests/currency-utils/test_currency_tools.py
Adds some more fuzz testing to the currency conversions.
> add more fuzz testing to currency conversions

- eth_utils/hexidecimal.py
- tests/address-utils/test_address_utils.py
- tests/hexidecimal-utils/test_is_hex.py
- tests/types-utils/test_types_utils.py
Plus a few flake8 complaints. There are more that I didn't have time to fix up in /tests this time, so I didn't add it to tox.ini.
> Capture Unicode errors in is_hex()

- .bumpversion.cfg
- README.md
- setup.py
Release process was institutional
Documented how to make releases.
> improve release process

- eth_utils/abi.py
- eth_utils/address.py
- eth_utils/crypto.py
- eth_utils/hexidecimal.py
Tidy up unnecessary future imports after deprecating py2 support
> Remove unnecessary future imports

- .gitignore
- README.md
- eth_utils/__init__.py
- eth_utils/conversions.py
- eth_utils/decorators.py
- tests/conversion-utils/test_conversions.py
#47 we want to use type conversion utils across several repositories
imported code from web3
> add type conversion helpers

- README.md
- eth_utils/__init__.py
- eth_utils/decorators.py
- tests/decorator-utils/test_combomethod.py
Want to use the `@combomethod` decorator in eth-account (and web3.py)
See #47 
Added it, and created a simple test
> add @combomethod decorator

- .travis.yml
Travis was not testing pypy3
Now it is, thanks to https://github.com/travis-ci/travis-ci/issues/9206
> Test Travis with pypy3

- eth_utils/currency.py
Needed to backport #45 into v0
Added logic from #45 into branch off latest stable v0
closes #46
> Backport pr45 into v0

- tests/conftest.py
@carver 👍 
Add autouse fixture to print warnings
> Add autouse fixture to print warnings

- setup.py
Fixes #74 
Use latest eth-hash
> upgrade eth-hash to stable 0.1.0

- eth_utils/address.py
- tests/address-utils/test_address_utils.py
```py
>>> assert not is_address('0x' + '00' * 19)
AssertionError
```
oops
Remove the `'0x'` prefix before doing the length check.
> 19 byte address should be invalid

- eth_utils/encoding.py
Just a bit of lint.
Took it out.
> Just a tiny bit of lint

- README.md
- eth_utils/address.py
- eth_utils/conversions.py
Noticed some grammatical errors.
Corrected them.
> Fix typos using "it's" as possessive

- eth_utils/applicators.py
- eth_utils/curried/__init__.py
- eth_utils/functional.py
- eth_utils/toolz.py
- setup.py
- tests/curried-utils/test_curried.py
> try conditional cytoolz or toolz install based on python implementation

- README.md
- eth_utils/address.py
- eth_utils/crypto.py
- eth_utils/currency.py
- eth_utils/debug.py
- eth_utils/encoding.py
- eth_utils/hexadecimal.py
- eth_utils/types.py
More modules need type-hints
Added type-hints to a couple more modules
> Add typehints to more modules

- eth_utils/address.py
- eth_utils/conversions.py
- eth_utils/typing/__init__.py
- eth_utils/typing/misc.py
- setup.py
Conversions module needed type hints
> Add type hints to conversions module

- CHANGELOG
The CHANGELOG has not been filled for the past few releases.
Looked through the releases and updated info on all stable releases
> Backfill CHANGELOG

- setup.py
Needs upgrade to eth_typing 2.0.0
Upgraded
> Update eth_typing to 2.0.0

- docs/releases.rst
Needed new release notes for v1.2.2
Added them.
> add v1.2.2 release notes

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- Makefile
- README.md
- newsfragments/117.feature.rst
- newsfragments/172.doc.rst
- newsfragments/README.md
- newsfragments/validate_files.py
- pyproject.toml
- setup.py
- tox.ini
> Added TownCrier

- eth_utils/typing/__init__.py
Doii: https://github.com/ethereum/eth-utils/pull/177#discussion_r350449002
> Fix ethpm_utils -> eth_utils typo

- MANIFEST.in
- newsfragments/182.bugfix.rst
> Missing asterisk in manifest

- docs/utilities.rst
- eth_utils/__init__.py
- eth_utils/curried/__init__.py
- eth_utils/humanize.py
- newsfragments/188.feature.rst
- tests/humanize-utils/test_humanize_integer_sequence.py
I found myself wanting this utility recently.  It's been living in the trinity codebase for a while and seems to work well.
copy/pasta from the Trinity codebase
> Add humanize_integer_sequence

- eth_utils/hexadecimal.py
There were a bunch of `type: ignores` that didn't make sense at first glance, since the `codecs.decode()` issue was closed on typeshed.
Then I noticed that the input argument is expected to be a `bytes` value. Fixing that meant we could drop the type ignores. It also seems that codecs just uses `binascii` under the hood, so we might as well go straight to the source, which provides a small performance benefit.
> unhexlify takes a bytes input, mandatory in py3.8

- eth_utils/address.py
After profiling an application I have that does a lot of ABI encoding and is CPU-bound, I discovered half of the time spent doing encoding is spent in `is_address()`. It is called a lot of times on every single address I encode (because so many functions depend on it).
This makes it much faster, and tries to avoid computing the same things over and over.
All tests should pass.
Here is a test script:
```
import eth_abi
import time
import timeit
test_address = "0xdac17f958d2ee523a2206206994597c13d831ec7"
addresses = [test_address] * 10
def f():
return eth_abi.encode_single("address[]", addresses)
print(timeit.timeit(f, number=10000))
```
It takes ~2 seconds to run on my machine before this patch, ~1.2 seconds after this patch.
> Performance optimization for is_address().

- .circleci/config.yml
- .github/pull_request_template.md
- .pre-commit-config.yaml
- .readthedocs.yaml
- MANIFEST.in
- Makefile
- docs/conf.py
- newsfragments/272.internal.rst
- pyproject.toml
- setup.py
- tests/core/applicator-utils/test_applicators.py
- tests/core/currency-utils/test_currency_tools.py
- tests/core/encoding-utils/test_big_endian_integer.py
- tests/core/functional-utils/test_type_inference.py
- tests/core/logging-utils/test_DEBUG2_logging.py
- tests/core/logging-utils/test_compat_with_abc_ABC.py
- tests/core/network-utils/test_network_utils.py
- tests/core/test_import_and_version.py
Merge template, fixing docs ci, adding nightly ci run
> Upgrade template

- setup.py
> Update `eth-typing` >=`5.0.0`
