ethereum/eth-utils

README.md, eth_utils/hexidecimal.py, tests/hexidecimal-utils/test_is_hex.py
`is_hex` had some surprising return values like:
```python
>>> is_hex('0x')
False
>>> is_hex('0x12345')  # odd length
False
```
Changed to accept both empty string hex values `0x` and odd-length hex values.
=> Modify is_hex to be more *right*

CHANGELOG, README.md, eth_utils/__init__.py
Fixes #31
There were a few places where the python library was referenced as `eth_utils` when it should have been `eth-utils`
Changed them to be `eth-utils`
=> fix places where python library was named eth_utils

.travis.yml, requirements-dev.txt, setup.py, tox.ini
Python 3.6 should be supported.
Expanded tests to test against 3.6
=> expand tests to 3.6

setup.py
Builds shouldn't automatically update major version of dependency.
Like https://github.com/ethereum/web3.py/pull/523
Lock down major version in setup.py. Note that pysha3 seems broken in <1 (at least at 0.3), so the major version was locked to `v1.*`.
=> Constrain dependencies to major version

eth_utils/currency.py
DefaultContext was being used to set precision.
Added precision as optional kwarg to allow users to set their own precision (@pipermerriam was this the right move?) and set precision using localcontext.
closes #44
=> Convert precision to localcontext

README.md, eth_utils/__main__.py, eth_utils/debug.py
People often leave out details of their environment when reporting a bug (or answer from memory). Let's make it painfully easy to report the info we want.
At shell, generate info with: `python -m eth_utils`
Example Output:
```sh
$ python -m eth_utils 
Python version:
3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406]
Operating System: Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty
pip freeze result:
apipkg==1.4
attrs==17.4.0
bumpversion==0.5.3
cytoolz==0.9.0
decorator==4.2.1
-e git+git@github.com:ethereum/eth-account.git@0812bb5bf31fa08e9be21d83ae79cd49681c6b16#egg=eth_account
eth-keyfile==0.4.1
eth-keys==0.1.0b4
-e git+git@github.com:ethereum/eth-rlp.git@b640ba7531cc04e2addf10f927fab91fb7015c2e#egg=eth_rlp
-e git+git@github.com:pipermerriam/ethereum-utils.git@0e1af14d44d …
```
=> Tool to generate environment info

README.md, eth_utils/__init__.py, eth_utils/applicators.py, eth_utils/conversions.py, eth_utils/curried/__init__.py, eth_utils/decorators.py, tests/applicator-utils/test_applicators.py, tests/curried-utils/test_curried.py
Wanted to use apply_formatters_to_dict in eth-account
Imported it, added doc and test. Then got carried away and imported many of the others, because it seems like they belong in the same place.
Notable changes proposed (in code) during the import:
- Reversed the order of the condition & formatter in `apply_one_of_formatters` to match the new order of `apply_formatter_if(condition, formatter)`
- Rename `apply_formatters_to_args` -> `combine_argument_formatters` because it's the only one that doesn't actually apply when you supply all the arguments.
=> Import many of the application functions from web3.py

eth_utils/__init__.py, eth_utils/address.py, eth_utils/curried/__init__.py, tests/address-utils/test_address_utils.py
@pipermerriam // @carver Thanks for the help on the other pr - broke it up to keep things simple but will use the old convo for reference.
Address utils used `force_bytes` / `force_text`
- deprecated `force_bytes` / `force_bytes` and dependent functions
- converted address utils to use `to_bytes` / `to_text` from `conversions.py`
- dropped support for 32byte addresses
=> Convert address utils from force text/bytes

eth_utils/abi.py, eth_utils/address.py, eth_utils/crypto.py
`keccak256()` used to be deprecated `force_bytes`
Converted function to use `to_bytes`
=> Convert keccak from force_bytes

.circleci/config.yml, .travis.yml, eth_utils/crypto.py, setup.py, tox.ini
Want to easily swap in keccak256 implementations.
Use eth-hash library, with no backend specified in eth-utils
=> Swap in eth-hash for pysha3

eth_utils/formatting.py, eth_utils/string.py
- force bytes/text utils and dependent functions needed to be deprecated.
- `.formatting` utils needed to be deprecated in favor of using stdlib functions
Deprecated appropriate functions.
=> Deprecate force bytes/text & formatting utils

eth_utils/conversions.py, eth_utils/decorators.py, tests/decorator-utils/test_validate_conversion_arguments.py
Non-text type arguments were getting processed by conversion functions
Updated decorator from `assert_one_val` to `validate_conversion_arguments` which is the same except it also validates that arguments for `hexstr` or `text` are of text type.
closes #60
=> Write validate conversion arguments decorator

eth_utils/conversions.py, eth_utils/decorators.py, tests/decorator-utils/test_validate_conversion_arguments.py
`to_hex` and `to_int` conversion function kwargs were not updated to be compatible with new decorator `validate_conversion_arguments`
Update kwargs
thanks for catching this @carver
=> Update hex and int conversions to work with new decorator

eth_utils/formatting.py, eth_utils/string.py, tests/conftest.py
Too many deprecation warnings logged in v0
Ignored the logging of deprecation warnings
closes #65
=> Ignore deprecation warnings

eth_utils/hexidecimal.py
decode_hex() was passed a bytes value, and it wasn't caught until deep in the eth-utils stack. 
Immediately reject non-str values to decode_hex
resolves #68
=> Strictly accept text types for decode_hex

README.md, eth_utils/__init__.py, eth_utils/applicators.py, eth_utils/curried/__init__.py, eth_utils/decorators.py, tests/applicator-utils/test_applicators.py
`combine_argument_formatters` sticks out as inconsistent with the other `apply_*` methods.
- In the existing API, it was not easily (feasibly?) curryable, so it could not be applied immediately.
- Because it couldn't be applied, naming it `apply_<something>` didn't make sense.
- But now it sticks out as inconsistent, and more difficult to remember the pattern
I'm just floating this concept. I think I like it, but I'm not 100% sure:
- Switch the API so that the formatters are supplied in an iterable in argument one, and then argument two has the iterable to apply the formatters to.
- The method is now curry-able
- The name can be more consistent, and still be semantically accurate
`apply_formatters_to_sequence` now applies each formatter to each position in the given sequence.
_Should we …
=> Apply formatters to sequence

eth_utils/applicators.py, tests/applicator-utils/test_applicators.py
`apply_key_map` behaved unpredictably with conflicting keys
Write a catch to recognize conflicting keys and raise a `KeyError`
=> Update apply key map to catch conflicting keys

eth_utils/encoding.py
Opportunity for speed improvements for `int_to_big_endian`
This implementation is 20% faster than the original.  The inlining of the `byte_length` gains an extra ~1-2% speed for what feels like a minor hit to readability.
```python
import time
import math
def profile(to_wrap, runs=100000):
start = time.time()
for i in range(1, runs + 1): to_wrap(i)
duration = time.time() - start
print(f'took {duration} s to run {runs} times. {duration*1000000/runs} us per run')
def int_to_big_endian(value):
byte_length = max(math.ceil(value.bit_length() / 8), 1)
return value.to_bytes(byte_length, byteorder='big')
def or_int_to_big_endian(value):
byte_length = math.ceil(value.bit_length() / 8) or 1
return value.to_bytes(byte_length, byteorder='big')
def new_int_to_big_endian(value):
return …
```
=> Faster int_to_big_endian implementation

README.md
Fixes #104 
Note that `is_hex(bytes_val)` will raise exception, in readme
=> readme: is_hex() raises on bytes argument

eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/module_loading.py, tests/module-loading-utils/test_import_string.py
This util is both used in `py-evm` and `py-ethpm` - so @cburgdorf suggested moving it to a shared location here.
Added the util to `module_loading.py`
=> Add import_string util from django

eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/exceptions.py, tests/curried-utils/test_curried.py
Libraries need a common `ValidationError` exception.
Added `ValidationError` to new `exceptions` module
fixes #114
=> Write ValidationError exception

setup.py
When I updated `py-ethpm` to use eth-utils `v1.1.1`, it installs eth-typing `v1.0.0` even though eth-typing is pinned to `>=1.1.0` in py-ethpm. 
pin eth-typing dependency to `>=1.1.0`
=> Update eth-typing version

setup.py
Solves #125
See ethereum/web3.py#1012 (comment)
Python 3.5.2 has a bug...
Added requirement string which excludes 3.5.2
=> Constraining Python Version 3.5.2

eth_utils/functional.py, fixtures/mypy/apply_to_return_value_decorator.py, fixtures/mypy/to_dict_decorator.py, fixtures/mypy/to_list_decorator.py, fixtures/mypy/to_ordered_dict_decorator.py, fixtures/mypy/to_set_decorator.py, fixtures/mypy/to_tuple_decorator.py, setup.py, tests/functional-utils/type_inference_tests.py, tox.ini
This is a follow up of the discussion @jannikluhn and I had [here](https://github.com/ethereum/py-evm/pull/555#discussion_r181344706)
Currently, every usage of  `apply_to_return_value` and all the related decorators such as `to_list`, `to_dict` etc basically erase valuable type information.
Consider this:
```python
@to_list
def return_tuple():
return (1, 2)
x = return_tuple()
x = 'foo'
```
Currently `mypy` does not catch this because it has no idea what `x` is and only recognizes it as `Any` leaving us vulnerable to such bugs.
Added type hints to `apply_to_return_value`. Now `mypy` is able to properly infer the type and catch these bugs.
Considering how much we rely on these decorators this change has a relatively high impact so I'm opening this PR early to evaluate if you'd be generally …
=> Add type hints to decorator

tests/abi-utils/test_abi_utils.py
The test cases for `collapse_if_tuple` did not cover two edge cases.
Added tests for them.
=> Add `collapse_if_tuple` test cases

setup.py
Fixes #140 
Added a `py.typed` file and made the corresponding change in `setup.py`
=> Enable discovery of type hints as per PEP561

eth_utils/decorators.py
Some minor lint found its way into the project.  Incorrectly using `is` for numerical equality check.
Changed to `==`.
=> Fix incorrect equality check

eth_utils/decorators.py, tox.ini
Tox was complaining about `make` being an external command.
Explicitly whitelisted it.
=> Tox config

eth_utils/conversions.py, eth_utils/functional.py, setup.py, tests/mypy_typing_of_functional_utils.py, tox.ini
The `to_dict` and `to_ordered_dict` had incorrect type hints.
Also updated to new `mypy` version that has some nice improvements
Added a test for each of the `to_thing` decorators to validate they do indeed preserve type data  correctly.
=> Fix type checking issue with to_dict and to_ordered_dict

docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/numeric.py, setup.py, tests/numeric-utils/test_clamp.py, tox.ini
It's not very easy to read a numeric clamp using the built-in primatives.
```
val = min(5, max(8, value))
val = tuple(sorted((5, 8) + (value,)))[1]
...
```
Added a new utility `clamp(...)` which does this.
=> Add numeric clamp utility

eth_utils/currency.py, setup.py, tests/currency-utils/test_denoms_obj.py, tests/mypy_typing_of_functional_utils.py
The `eth_utils.denoms` object doesn't have type information for it's attributes since it is dynamically created using `type(...)`
Updated it to explicitly name all of the units and added a test to ensure that all units from `eth_utils.units` are present on the class.
=> Make denoms a real class

eth_utils/decorators.py, tests/mypy_typing_of_functional_utils.py, tox.ini
The `replace_exceptions` helper had incorrect type hints.
Fixed type hints to expect classes instead of instances.
=> Fix type hinting for replace_exceptions

.circleci/config.yml, eth_utils/typing/misc.py, tox.ini
`eth_utils` defined own type aliases and doesn't use the ones that `eth_typing` provides. See #160 
Used the type aliases from `eth-typing`.
This is a second attempt, according to the comment: https://github.com/ethereum/eth-utils/pull/161#issuecomment-495556352
=> Use eth-typing types

docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/humanize.py, tests/humanize-utils/test_humanize_ipfs_uri.py
This is a util that could be helpful to have available when working with ipfs uris.
=> Write humanize_ipfs_uri

Makefile, docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/logging.py, tests/logging-utils/test_compat_with_abc_ABC.py, tests/logging-utils/test_compat_with_typing_Generic.py, tests/logging-utils/test_has_logger_metaclass.py, tests/type-checks/mypy_typing_of_has_logger.py
The utils committed previously in #158 didn't play well with other metaclasses.
1. Expose the metaclasses as public APIs
2. Add a convenience API onto the `HasLoggerMeta` for combining it with another Metaclass to make python happy.
3. Add tests that ensure that usage of `HasLoggerMeta` in conjunction with `abc.ABCMeta` or `typing.GenericMeta` work as expected.
=> fixup extended debug logging utils

.circleci/config.yml, Makefile, setup.py, tests/logging-utils/test_compat_with_typing_Generic.py, tox.ini
Not tested support for python3.7
Added CI test run for 3.7 (including a linting run against 3.7)
=> Add support for python3.7

eth_utils/logging.py, tests/logging-utils/test_DEBUG2_logging.py
`DEBUG2` implements some performance issues with the overhead of determining if logs should be shown for a given level each time the function is called.
We fully cache whether the log level is enabled as well as turning the `ExtendedDebugLogger.debug2` function into a noop in the event that `DEBUG2` is disabled.
=> caching of checks for whether to log at DEBUG2 levels

eth_utils/__init__.py, eth_utils/logging.py, tests/logging-utils/test_DEBUG2_logging.py, tests/logging-utils/test_compat_with_typing_Generic.py
The logging level for `DEBUG2` was not exposed in the primary public API.
Added it to the main `eth_utils` top level import API.
=> Expose the DEBUG2 logging level variable as top level import.

docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/logging.py, newsfragments/170.feature.rst, tests/logging-utils/test_get_logger.py
The metaclass approach to installing loggers is nice but it turns out it's really hard to use because it doesn't play well with other metaclasses and you have to do a [a lot of really gross boilerplate](https://github.com/ethereum/py-evm/blob/8a1052f7bc04b744d20ffcb3f947bc5857c1e16c/eth/abc_compat.py) to make it work.
This PR exposes two new utilties, `get_logger` and `get_extended_debug_logger`.
`get_logger` is like `logging.getLogger` but it takes an additional `logger_class` which dictates the type of logger that should be returned.
`get_extended_debug_logger` is just an implementation of `get_logger` that always returns an `ExtendedDebugLogger`.
=> add get_logger and get_extended_debug_logger

.circleci/config.yml, newsfragments/174.feature.rst, setup.py, tox.ini
python3.8 support was missing.
Added support for python3.8 by updating the version of libraries that were breaking with python3.8.
=> Add python3.8 support

eth_utils/hexadecimal.py, newsfragments/175.misc.rst
Some functions in the `hexadecimal` module are better suited to using `HexStr` types rather than a simple `str`
=> Update hexstr type hints

eth_utils/applicators.py, eth_utils/curried/__init__.pyi, newsfragments/180.misc.rst, tests/type-checks/mypy_typing_of_curried_utils.py
Re: #156 
`apply_formatter_if` is used quite liberally in `web3` and each one requires a `type: ignore`, but not anymore with the overload types implemented.
=> Add type overload to curried fn apply_formatter_if

MANIFEST.in, eth_utils/decorators.py, newsfragments/181.misc.rst
-  `.pyi` files were not being included in the distributions.
- Fix broken `combomethod` type hints.
Added a `global-include` for `.pyi` files in `MANIFEST.in`
=> Add interface files to MANIFEST.in

eth_utils/currency.py
The type hint for `to_wei` only allows ints, but the implementation also accepts floats, strs, and Decimals.
Updated type hint for `float`, `str` and `Decimal` as requested in issue #168
=> Update type hint for to_wei [Fixes: #168]

docs/utilities.rst, eth_utils/__init__.py, eth_utils/address.py, eth_utils/conversions.py, eth_utils/curried/__init__.py, eth_utils/curried/__init__.pyi, eth_utils/hexadecimal.py, newsfragments/137.feature.rst, tests/address-utils/test_address_utils.py, tests/hexadecimal-utils/test_is_hex.py, tests/hexadecimal-utils/test_is_hexstr.py
Fixes #137, it was decided that a second function `is_hexstr` should be added that returns False on any
non-string input call to the function.
The specified function was implemented.
- [ X] Clean up commit history
- [ X] Add entry to the [release notes](https://github.com/ethereum/trinity/blob/master/newsfragments/README.md)
=> Add is_hexstr function

eth_utils/hexadecimal.py, newsfragments/185.feature.rst
I have witnessed more than one `web3.py`-based application which was spending significant share of cpu time (~ 25%-50%) in this specific hex string validation loop.
The new implementation of `is_hex()` and `is_hexstr()` yields significant performance improvement over the previous approach, the new implementation can be about 40x faster according to my tests.
=> Using regular expression matching in `is_hex()` and `is_hexstr()`

eth_utils/types.py
Importing ABC directly from collections was deprecated.
Use collections.abc instead
Fixes #184
=> Import ABC from collections.abc instead of collections for Python 3 compatibility

eth_utils/logging.py, newsfragments/199.bugfix.rst, tests/logging-utils/test_get_logger.py
`logging.Logger.__reduce__()` returns (getLogger, name), which could give
us a regular Logger instance after pickling/unpickling an
ExtendedDebugLogger (e.g. when crossing process boundaries since the
other process wouldn't have an ExtendedDebugLogger with that name in the
logging module's cache).
=> Fix pickling of ExtendedDebugLogger

eth_utils/applicators.py, eth_utils/curried/__init__.py, newsfragments/201.feature.rst, newsfragments/201.misc.rst, setup.py, tests/applicator-utils/test_applicators.py, tests/functional-utils/type_inference_tests.py
- Web3py needed some curried functions, so I added those. 
- Bumped up mypy because typed-ast doesn't work with python 3.8
- Got rid of some deprecation warnings in the tests
Let me know if I should split this into 3 PRs.
Following [this PR](https://github.com/ethereum/eth-utils/pull/200)
=> Update a few curried functions for web3 and update mypy

eth_utils/applicators.py
When catching a TypeError or ValueError, we can't necessarily
re-initialize it with a string message argument. For example, a
JSONDecodeError requires a `doc` and `pos` argument.
Instead, we just re-raise with a new TypeError or ValueError, depending
on the subclass caught.
Got an inscrutable error message:
```
~/code/ens-doteth/venv-py3.8.0/lib/python3.8/site-packages/eth_utils/applicators.py in apply_formatters_to_dict(formatters, value)
84                 yield key, formatters[key](item)
85             except (TypeError, ValueError) as exc:
---> 86                 raise type(exc)(
87                     "Could not format value %r as field %r" % (item, key)
88                 ) from exc
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'
```
Turns out that it …
=> Raise known error instead of a blind re-raise

eth_utils/hexadecimal.py
I don't understand why all this code was present : if it's valid hex it will be decoded successfully, there is no way otherwise.
This also makes it faster because it's only about matching a regexp now. And simpler to understand.
All tests are passing.
=> Cleanup / optimization of is_hexstr().

eth_utils/address.py, newsfragments/205.bugfix.rst, tests/address-utils/test_address_utils.py
These methods actually support canonical address inputs, but didn't have tests or type signatures that indicate so:
- to_canonical_address
- to_checksum_address
- to_normalized_address
Add tests, update type annotations.
=> Allow Address as input to address conversions

eth_utils/crypto.py, newsfragments/208.internal.rst, setup.py
Have to cast/ignore the types from eth-hash, because they weren't being executed.
Get the latest type exports from eth-hash v0.3.0
=> Upgrade eth-hash to v0.3.0

eth_utils/hexadecimal.py, newsfragments/223.performance.rst
Nothing wrong, simply trying to improve performances here, and there.
I used that script to naively benchmark changes for the 2nd commit:
```python
import re
from timeit import timeit
def original(value, regex=re.compile("(0x)?[0-9a-f]*", re.IGNORECASE | re.ASCII)):
return regex.fullmatch(value) is not None
def new(value, regex=re.compile("(0[xX])?[0-9a-fA-F]*")):
return regex.fullmatch(value) is not None
print("original(True)", timeit(
"original('0x5831e66b7de5df2d8d4705c86c844ff60a50efcec53f9449b16dc43216a783f7')", "from __main__ import original"))
print("new(True)", timeit(
"new('0x5831e66b7de5df2d8d4705c86c844ff60a50efcec53f9449b16dc43216a783f7')", "from __main__ import new"))
print()
print("original(False)", timeit(
"original('0x5831e66b7de5df2d8d4705c86c844ff60a50efcec53f9449b16dc432 …
```
=> Hexadecimal optimizations

eth_utils/address.py, eth_utils/logging.py, newsfragments/226.misc.rst, pytest.ini, setup.py, tests/functional-utils/type_inference_tests.py
mypy v0.720 isn't compatible with Python 3.10.
Bumped the mypy version requirement and fixed new errors. Also had to do some mucking around with `docs/conf.py` and `.bumpversion.cfg` because of black autoformatting. The autoformatting changes are duplicated in #225.
=> Update mypy, fix new errors

eth_utils/logging.py, newsfragments/232.internal.rst, setup.py
Issue #159
Replace `cached_show_debug2_property` with `cached_property`, and add the cached-property package in `install_requires`.
`cached_property` has the [untyped issue](https://github.com/pydanny/cached-property/issues/172), so I add the `# type: ignore`.
=> refactor: Use cached_property to cache the show_debug2

newsfragments/235.misc.rst, newsfragments/README.md, newsfragments/validate_files.py, pyproject.toml
Missing `beaking` type for newsfragments.
Copy `towncrier` related files from the ethereum-python-project-template.
=> Copy `towncrier` types from project template

.circleci/config.yml, .readthedocs.yaml, docs/conf.py, newsfragments/239.internal.rst, setup.py, tox.ini
Docs dependencies can be bumped and unnecessary ones removed
Bumped and removed, plus tox.ini whitelist -> allowlist, and remove all upper-bounds  while I was here.
=> bump docs dependencies & remove unneeded

newsfragments/231.internal.rst, tests/currency-utils/test_currency_tools.py
Issue #102
Add `float` inputs to see that `from_wei(to_wei(value, 'ether'), 'ether') == decimal.Decimal(str(value))` for `float` inputs.
When the decimal of the value is less than 0 Wei, `to_wei` converts it to 0, and the test case gets `AssertionError` because of 0 != 0.0...01.
=> test: add currency tests with float ether input

docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/humanize.py, newsfragments/194.feature.rst, tests/humanize-utils/test_humanize_wei.py, tests/type-checks/mypy_typing_of_curried_utils.py
Closes #194 
Added function to convert units of ether to other more reader-friendly units.
=> Added `humanize_wei` function

.readthedocs.yml, newsfragments/250.internal.rst
ReadTheDocs will soon require a `build.os` to be explicitly configured
Added to readthedocs.yml
=> add build.os to rtd settings

.gitignore, eth_utils/__init__.py, newsfragments/242.misc.rst
This package is deprecated
Related to Issue #242
Closes #242
Remove `pkg_resources` import above 3.8
=> Remove pkg_resources 

newsfragments/256.internal.rst, tests/network-utils/test_network_utils.py
Tests failed after networks were updated.
Use large values for invalid `chainId`s that will likely never exist.
=> Separate Network chainId tests from exception cases

newsfragments/263.internal.rst, pyproject.toml, tests/core/test_import.py, tests/core/test_import_and_version.py
Some bools in `pyproject.toml` the wrong type - changed `"True"` to `true`.
Added a test to make sure the `__version__` attribute is available for the lib.
=> correct format of pyproject.toml bools and add test for __version__

eth_utils/address.py, newsfragments/265.breaking.rst, tests/address-utils/test_address_utils.py
Relates to https://github.com/ethereum/web3.py/issues/715
Closes #246 
Removed validation of checksummed addresses from the `Web3.is_address` utility.
=> `Web3.is_address` no longer requires checksummed addresses

newsfragments/269.internal.rst, setup.py
`cached_property` is only installed if <=py37, which was dropped a while ago.
Removed it from deps.
=> remove cached_property if <py38 dependency

eth_utils/network.py, newsfragments/278.internal.rst
When networks are changed but get out of sync between eth-typing and eth-utils, warnings are thrown.
Remove the warning, very few core networks change much. If folks need net networks, they can be added with the script.
Planning to add a CI process to run the script automatically.
=> Remove network warning spam

.pre-commit-config.yaml, docs/contributing.rst, docs/utilities.rst, eth_utils/__init__.py, eth_utils/abi.py, eth_utils/curried/__init__.py, newsfragments/271.breaking.rst, newsfragments/271.feature.rst, setup.py, tests/core/abi-utils/test_abi_utils.py, tests/mypy/abi_types.py
Contract ABI utilities are useful for encoding and decoding contract transactions. Many utilities are implemented in web3.py as private methods.
Related to https://github.com/ethereum/web3.py/issues/3036
Many of these functions were previously private in `web3.py` but these public utilities are used as of `v7`. See
https://github.com/ethereum/web3.py/pull/3408
Implement functions for parsing and validating contract data using the ABI spec.
The following functions have been added to the `eth_utils.abi` module:
`abi_to_signature`,
`collapse_if_tuple`,
`filter_abi_by_name`,
`filter_abi_by_type`,
`get_abi_input_names`,
`get_abi_input_types`,
`get_abi_output_names`,
`get_abi_output_types`,
`get_aligned_abi_inputs`,
`get_all_event_abis`,
`get_all_function_abis`,
`get_normalized_abi_inputs`,
=> Utilities for Contract ABIs

.pre-commit-config.yaml, newsfragments/282.internal.rst, setup.py, tox.ini
Running `mypy` in a `pre-commit` container can miss local context.
Run `mypy` locally via a `pre-commit` hook. No new issues.
Bumped to `mypy==1.10.0`
=> run mypy linting locally

newsfragments/284.bugfix.rst, setup.py
PR #271 introduced `hexbytes` as a unnecessary install dependency. This introduces a cyclic dependency with `hexabytes` which depends on `eth-utils` in its testsuite: https://github.com/ethereum/hexbytes/blob/main/setup.py#L24 
This PR removes this dependency again. This fixes the cyclic dependency.
=> setup: Remove cyclic dependency

docs/utilities.rst, eth_utils/__init__.py, eth_utils/curried/__init__.py, eth_utils/humanize.py, newsfragments/285.feature.rst, tests/core/humanize-utils/test_humanize_hex_str.py, tests/core/humanize-utils/test_humanize_hexstr.py
@antazoey had an open PR to add this a while back. I couldn't get the branch to work correctly, so cherry picked the commits and added the ability to pass in a hex string that starts with '0x'. 
Closes #220 
Added a new function called `humanize_hexstr`.
=> Humanize hexstr

eth_utils/logging.py, newsfragments/275.feature.rst
The `_BaseHasLogger` and `_BaseHasExtendedDebugLogger` is unnecessary
Related to Issue #262
Closes #262
Removed these classes and update the main class
=> ♻️ remove deprecated classes

eth_utils/curried/__init__.py, eth_utils/decorators.py, eth_utils/network.py, eth_utils/numeric.py, newsfragments/288.internal.rst, newsfragments/288.misc.rst, setup.py, tests/functional-utils/test_type_inference.py, tests/logging-utils/test_compat_with_abc_ABC.py
Network warnings visible when the network constants are out of date. There is no need to send warnings, especially since the core networks are already present. If a new network is needed, the script can be run separately to update the networks file.
Remove the warning for missing networks and allow initialization from the network list.
=> Remove warning for missing networks

eth_utils/address.py, newsfragments/289.bugfix.rst
The signature of `is_same_address` requires both arguments to be `eth_typing.AnyAddress`, but actually, the source code of the function allows any string to be provided. And mypy raise an error.
Related to Issue #221
Closes #221
For some reason, mypy cannot automatically recognize that bytes correspond to `AnyStr`. This might be related to the fact that `TypeVar` doesn't always work as expected when it comes to type unions. Therefore, I make to `Union[AnyAddress, str, bytes]` instead `Union[AnyAddress, AnyStr]`
=> refactor(address): accept types AnyAddress, str, bytes

docs/utilities.rst, eth_utils/__init__.py, eth_utils/applicators.py, eth_utils/curried/__init__.py, eth_utils/pydantic.py, newsfragments/303.feature.rst, setup.py, tests/core/applicator-utils/test_applicators.py, tests/core/pydantic-utils/test_camel_model.py
Related to Issues:
- Moves the work done in ethereum/eth-account#316 ethereum/eth-account#318 to *eth-utils* for standardization / use across ethereum python libraries.
- These changes allow expected validated pydantic models (`CamelModel`) to be serialized to JSON-RPC expected types when appropriate.
- Since JSON-RPC objects could be `CamelModel` classes, open the expected types to allow for this model in ``apply_formatters_to_dict()``.
Beyond this PR, `eth-account` should be updated to use this model, making sure no breaking changes are introduced, so that those models are not excluded from any class checks across our repos.
I'm not sure if an animal that formats other animals with a computer is cute... I think this is terrifying in a way 😬 . Thanks, chatGPT.
=> Add CamelModel pydantic model for use across libraries

eth_utils/abi.py, newsfragments/299.bugfix.rst
Raised `KeyError` exception when `name` field not in `ABIComponent`
Related to Issue #297
Closes #297
Replace `arg["name"]` with `arg.get("name")`
And I think we need to update `ABIElement` in `eth-typing` because names are optional
=> 🩹 use `arg.get` in `get_abi_input_names` and `get_abi_output_names`
